In [1]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data

a  1    1.444420
   2   -2.279286
   3    0.154565
b  1   -2.046843
   2    0.127152
c  3    1.829365
   1   -1.704532
d  2   -0.033601
   3    1.275404
dtype: float64

In [2]:
data1 = data.unstack()
data1

          1         2         3
a  1.444420 -2.279286  0.154565
b -2.046843  0.127152       NaN
c -1.704532       NaN  1.829365
d       NaN -0.033601  1.275404

In [3]:
data1.stack()

a  1    1.444420
   2   -2.279286
   3    0.154565
b  1   -2.046843
   2    0.127152
c  1   -1.704532
   3    1.829365
d  2   -0.033601
   3    1.275404
dtype: float64

In [4]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [5]:
frame1 = frame.stack(['顏色','縣市'])
frame1

C:\Users\user\AppData\Local\Temp\ipykernel_24448\3801192309.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  frame1 = frame.stack(['顏色','縣市'])

key1  key2  顏色     縣市
a     1     Green  台北     0.0
                   台中     2.0
            Red    台北     1.0
      2     Green  台北     3.0
                   台中     5.0
            Red    台北     4.0
b     1     Green  台北     6.0
                   台中     8.0
            Red    台北     7.0
      2     Green  台北     9.0
                   台中    11.0
            Red    台北    10.0
dtype: float64

In [6]:
frame1.unstack('key1')

key1             a     b
key2 顏色    縣市
1    Green 台北  0.0   6.0
           台中  2.0   8.0
     Red   台北  1.0   7.0
2    Green 台北  3.0   9.0
           台中  5.0  11.0
     Red   台北  4.0  10.0

In [7]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.713905  0.358378
1    a  two -1.250709 -0.264966
2    b  one  1.144140  0.249825
3    b  two  0.450026 -1.410199
4    a  one  0.067816  0.026268

In [8]:
df.groupby('key1').sum()

           key2     data1     data2
key1
a     onetwoone -0.468989  0.119681
b        onetwo  1.594166 -1.160374