In [1]:
import numpy as np
import pandas as pd

tips_df = pd.read_csv('tips.csv')
tips_df.columns = ['總票價', '小費', '吸煙者', '日期', '時間', '大小']
tips_df

       總票價    小費  吸煙者    日期      時間  大小
0    16.99  1.01   No   Sun  Dinner   2
1    10.34  1.66   No   Sun  Dinner   3
2    21.01  3.50   No   Sun  Dinner   3
3    23.68  3.31   No   Sun  Dinner   2
4    24.59  3.61   No   Sun  Dinner   4
..     ...   ...  ...   ...     ...  ..
239  29.03  5.92   No   Sat  Dinner   3
240  27.18  2.00  Yes   Sat  Dinner   2
241  22.67  2.00  Yes   Sat  Dinner   2
242  17.82  1.75   No   Sat  Dinner   2
243  18.78  3.00   No  Thur  Dinner   2

[244 rows x 6 columns]

In [2]:
tips_df['小費比例'] = tips_df['小費'] / tips_df['總票價']
tips_df

       總票價    小費  吸煙者    日期      時間  大小      小費比例
0    16.99  1.01   No   Sun  Dinner   2  0.059447
1    10.34  1.66   No   Sun  Dinner   3  0.160542
2    21.01  3.50   No   Sun  Dinner   3  0.166587
3    23.68  3.31   No   Sun  Dinner   2  0.139780
4    24.59  3.61   No   Sun  Dinner   4  0.146808
..     ...   ...  ...   ...     ...  ..       ...
239  29.03  5.92   No   Sat  Dinner   3  0.203927
240  27.18  2.00  Yes   Sat  Dinner   2  0.073584
241  22.67  2.00  Yes   Sat  Dinner   2  0.088222
242  17.82  1.75   No   Sat  Dinner   2  0.098204
243  18.78  3.00   No  Thur  Dinner   2  0.159744

[244 rows x 7 columns]

In [4]:
grouped = tips_df.groupby(['日期','吸煙者'])
grouped_pct = grouped['小費']
grouped_pct.mean().unstack('吸煙者')

吸煙者         No       Yes
日期
Fri   2.812500  2.714000
Sat   3.102889  2.875476
Sun   3.167895  3.516842
Thur  2.673778  3.030000

In [5]:
grouped = tips_df.groupby(['日期','吸煙者'])
grouped_pct = grouped[['小費','小費比例']]
grouped_pct.mean().unstack('吸煙者')

            小費                小費比例
吸煙者         No       Yes        No       Yes
日期
Fri   2.812500  2.714000  0.151650  0.174783
Sat   3.102889  2.875476  0.158048  0.147906
Sun   3.167895  3.516842  0.160113  0.187250
Thur  2.673778  3.030000  0.160298  0.163863

In [6]:
grouped = tips_df.groupby(['日期','吸煙者'])
grouped_pct = grouped['小費']
grouped_pct.agg(['mean','std'])

              mean       std
日期   吸煙者
Fri  No   2.812500  0.898494
     Yes  2.714000  1.077668
Sat  No   3.102889  1.642088
     Yes  2.875476  1.630580
Sun  No   3.167895  1.224785
     Yes  3.516842  1.261151
Thur No   2.673778  1.282964
     Yes  3.030000  1.113491

In [7]:
grouped = tips_df.groupby(['日期','吸煙者'])
grouped_pct = grouped['小費']
grouped_pct.agg([('小費平均','mean'),('小費標準差','std')])

              小費平均     小費標準差
日期   吸煙者
Fri  No   2.812500  0.898494
     Yes  2.714000  1.077668
Sat  No   3.102889  1.642088
     Yes  2.875476  1.630580
Sun  No   3.167895  1.224785
     Yes  3.516842  1.261151
Thur No   2.673778  1.282964
     Yes  3.030000  1.113491

In [8]:
grouped = tips_df.groupby(['日期','吸煙者'])
grouped_pct = grouped[['總票價','小費']]
grouped_pct.agg([('平均','mean'),('最大值','max'),('數量','count')])

                總票價                   小費
                 平均    最大值  數量        平均    最大值  數量
日期   吸煙者
Fri  No   18.420000  22.75   4  2.812500   3.50   4
     Yes  16.813333  40.17  15  2.714000   4.73  15
Sat  No   19.661778  48.33  45  3.102889   9.00  45
     Yes  21.276667  50.81  42  2.875476  10.00  42
Sun  No   20.506667  48.17  57  3.167895   6.00  57
     Yes  24.120000  45.35  19  3.516842   6.50  19
Thur No   17.113111  41.19  45  2.673778   6.70  45
     Yes  19.190588  43.11  17  3.030000   5.00  17

In [9]:
grouped = tips_df.groupby(['日期','吸煙者'])
grouped_pct = grouped[['總票價','小費']]
result = grouped_pct.agg([('平均','mean'),('最大值','max'),('數量','count')])
result['總票價'][['最大值','數量']]

            最大值  數量
日期   吸煙者
Fri  No   22.75   4
     Yes  40.17  15
Sat  No   48.33  45
     Yes  50.81  42
Sun  No   48.17  57
     Yes  45.35  19
Thur No   41.19  45
     Yes  43.11  17

In [10]:
grouped = tips_df.groupby(['日期','吸煙者'])
grouped_pct = grouped['小費']
grouped_pct.agg([('小費平均','mean'),('小費標準差','std')])

              小費平均     小費標準差
日期   吸煙者
Fri  No   2.812500  0.898494
     Yes  2.714000  1.077668
Sat  No   3.102889  1.642088
     Yes  2.875476  1.630580
Sun  No   3.167895  1.224785
     Yes  3.516842  1.261151
Thur No   2.673778  1.282964
     Yes  3.030000  1.113491