In [15]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame
# --------------------------------------------------
# 1. 生成隨機分數資料 (NumPy 陣列)
# --------------------------------------------------
# 隨機生成 50 到 100 之間的整數，形狀為 50 列 5 行 (50位學生、5個科目)
scores = np.random.randint(50, 101, size=(50, 5))

# --------------------------------------------------
# 2. 將 NumPy 陣列轉換成 Pandas DataFrame 資料表
# --------------------------------------------------
scores_df = pd.DataFrame(scores,                             # 傳入剛剛生成的隨機分數數據
            columns=['國文', '英文', '數學', '地理', '歷史'],  # 指定這 5 行的欄位名稱 (科目)
            index=range(1,51))                               # 指定這 50 列的列索引 (座號 1 到 50)
scores_df.T

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
國文,96,94,87,66,100,76,71,81,59,98,...,100,100,94,50,100,79,96,53,83,69
英文,62,64,63,57,84,55,83,85,81,55,...,63,90,97,65,88,53,68,67,62,98
數學,94,96,60,51,74,83,64,96,56,68,...,61,90,56,96,85,96,72,76,72,99
地理,61,98,72,63,90,62,99,66,57,51,...,95,85,88,59,80,99,65,98,54,50
歷史,57,68,68,86,72,56,67,78,61,85,...,58,50,95,65,89,51,64,51,77,95

In [1]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
scores_df

     姓名 性別   國文  英文  數學  地理  歷史
1   劉彥宏  男   66  66  89  99  87
2   曾彥廷  男   69  53  73  50  65
3   吳子睿  男   63  69  86  82  79
4   蕭志明  男   72  52  73  91  95
5   王文傑  男   75  98  82  60  99
6   朱冠霖  男   80  60  85  62  95
7   謝欣蓉  女   77  89  71  81  86
8   羅淑芬  女   88  70  51  65  71
9   許美慧  女   71  55  58  58  60
10  廖志豪  男   58  67  72  99  51
11  葉柏翰  男   67  85  96  70  85
12  呂承恩  男   63  60  93  90  65
13  蘇雅婷  女  100  76  95  57  89
14  高浩宇  男   67  99  59  80  70
15  王婉茹  女   59  76  85  85  61
16  莊承翰  男   72  66  76  82  81
17  黃裕傑  男   50  88  82  92  82
18  王冠廷  男   59  59  99  71  91
19  呂婉慧  女   56  51  51  84  94
20  莊子謙  男   68  80  50  86  73
21  蘇彥宏  男   65  84  57  63  97
22  李柏融  男   73  70  66  61  67
23  曾明軒  男   51  81  56  88  67
24  呂佳瑩  女   95  94  97  78  50
25  洪怡君  女   58  51  74  71  92
26  洪柏宏  男   83  87  77  73  90
27  江雅琪  女   76  86  64  54  57
28  郭怡萱  女   93  52  81  59  51
29  簡婉慧  女   69  63  87  56  85
30  楊靜宜  女   72  67  50  91  76
31  曾靜儀  女   70  91  67  66  55
32  蕭怡伶  女   70  89  97  81  82
33  洪裕豪  男   73  63  53  53  67
34  簡建宏  男   97  56  61  75  87
35  劉浩然  男   62  66  77  87  69
36  蕭浩宇  男   89  61  90  74  68
37  呂怡靜  女   60  84  55  89  75
38  邱宗翰  男   60  52  75  90  53
39  彭美慧  女   60  62  98  86  74
40  劉靜芬  女   56  70  51  89  72
41  許淑芬  女   62  91  85  77  97
42  邱裕豪  男   85  91  59  73  92
43  吳雅萍  女   99  84  76  68  95
44  施子軒  男   60  56  69  92  75
45  莊柏融  男   87  64  97  94  53
46  鍾浩銘  男   57  88  81  97  72
47  周美玲  女   56  62  60  63  89
48  劉婉婷  女   68  67  92  70  53
49  曾明哲  男   81  64  90  80  58
50  詹柏翰  男   94  61  85  53  83

In [2]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理   歷史
6   朱冠霖  男  89  53  60  97   54
7   謝欣蓉  女  79  66  84  80   57
8   羅淑芬  女  73  84  60  96   63
9   許美慧  女  60  74  52  96   61
10  廖志豪  男  50  86  99  67  100

In [3]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文  英文   數學  地理   歷史   總分    平均    排名
44  施子軒  男   88  87   91  80  100  446  89.2   1.0
32  蕭怡伶  女   82  77   77  98   98  432  86.4   2.0
24  呂佳瑩  女  100  73   82  83   87  425  85.0   3.0
46  鍾浩銘  男   85  98   93  76   67  419  83.8   4.0
16  莊承翰  男   79  89   60  90   90  408  81.6   5.0
40  劉靜芬  女   92  99   55  77   85  408  81.6   5.0
43  吳雅萍  女   70  97   82  96   58  403  80.6   7.0
21  蘇彥宏  男   73  59  100  84   87  403  80.6   7.0
11  葉柏翰  男   93  79   53  84   93  402  80.4   9.0
10  廖志豪  男   50  86   99  67  100  402  80.4   9.0
37  呂怡靜  女   67  97   76  63   93  396  79.2  11.0
19  呂婉慧  女   86  89   52  89   74  390  78.0  12.0
20  莊子謙  男   88  69   73  83   76  389  77.8  13.0
22  李柏融  男   90  70   98  51   74  383  76.6  14.0
13  蘇雅婷  女   88  88   65  82   58  381  76.2  15.0
23  曾明軒  男   96  88   89  58   50  381  76.2  15.0
14  高浩宇  男   79  75   68  80   74  376  75.2  17.0
8   羅淑芬  女   73  84   60  96   63  376  75.2  17.0
3   吳子睿  男   75  76   66  92   66  375  75.0  19.0
12  呂承恩  男   83  89   55  60   88  375  75.0  19.0
28  郭怡萱  女   55  88   92  82   57  374  74.8  21.0
25  洪怡君  女   68  90   90  59   67  374  74.8  21.0
45  莊柏融  男   92  89   85  54   52  372  74.4  23.0
47  周美玲  女   69  59   75  78   90  371  74.2  24.0
5   王文傑  男   84  83   93  55   52  367  73.4  25.0
7   謝欣蓉  女   79  66   84  80   57  366  73.2  26.0
39  彭美慧  女   70  60   90  89   52  361  72.2  27.0
26  洪柏宏  男   58  69   81  65   88  361  72.2  27.0
15  王婉茹  女   94  77   78  57   55  361  72.2  27.0
18  王冠廷  男   62  93   56  90   57  358  71.6  30.0
35  劉浩然  男   60  75   71  94   58  358  71.6  30.0
17  黃裕傑  男   90  55   60  61   89  355  71.0  32.0
4   蕭志明  男   61  86   55  73   78  353  70.6  33.0
34  簡建宏  男   52  89   66  57   89  353  70.6  33.0
6   朱冠霖  男   89  53   60  97   54  353  70.6  33.0
48  劉婉婷  女   85  50   81  53   83  352  70.4  36.0
42  邱裕豪  男   78  66   59  82   64  349  69.8  37.0
41  許淑芬  女   71  70   73  63   66  343  68.6  38.0
9   許美慧  女   60  74   52  96   61  343  68.6  38.0
29  簡婉慧  女   92  55   88  52   53  340  68.0  40.0
1   劉彥宏  男   96  51   50  73   69  339  67.8  41.0
27  江雅琪  女   63  53   86  77   60  339  67.8  41.0
50  詹柏翰  男   72  92   51  52   69  336  67.2  43.0
33  洪裕豪  男   52  53   78  71   69  323  64.6  44.0
36  蕭浩宇  男   84  57   52  62   67  322  64.4  45.0
38  邱宗翰  男   61  77   63  56   65  322  64.4  45.0
31  曾靜儀  女   59  62   75  53   73  322  64.4  45.0
49  曾明哲  男   53  92   61  51   62  319  63.8  48.0
2   曾彥廷  男   71  80   60  51   52  314  62.8  49.0
30  楊靜宜  女   53  79   51  68   52  303  60.6  50.0

In [4]:
from pandas import Series
def calulate(s:Series)-> int:
    n = (s < 60).sum()
    return n
    
scores_df['及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
scores_df

     姓名 性別   國文  英文   數學  地理   歷史   總分    平均    排名  及格的科目數
1   劉彥宏  男   96  51   50  73   69  339  67.8  41.0       2
2   曾彥廷  男   71  80   60  51   52  314  62.8  49.0       2
3   吳子睿  男   75  76   66  92   66  375  75.0  19.0       0
4   蕭志明  男   61  86   55  73   78  353  70.6  33.0       1
5   王文傑  男   84  83   93  55   52  367  73.4  25.0       2
6   朱冠霖  男   89  53   60  97   54  353  70.6  33.0       2
7   謝欣蓉  女   79  66   84  80   57  366  73.2  26.0       1
8   羅淑芬  女   73  84   60  96   63  376  75.2  17.0       0
9   許美慧  女   60  74   52  96   61  343  68.6  38.0       1
10  廖志豪  男   50  86   99  67  100  402  80.4   9.0       1
11  葉柏翰  男   93  79   53  84   93  402  80.4   9.0       1
12  呂承恩  男   83  89   55  60   88  375  75.0  19.0       1
13  蘇雅婷  女   88  88   65  82   58  381  76.2  15.0       1
14  高浩宇  男   79  75   68  80   74  376  75.2  17.0       0
15  王婉茹  女   94  77   78  57   55  361  72.2  27.0       2
16  莊承翰  男   79  89   60  90   90  408  81.6   5.0       0
17  黃裕傑  男   90  55   60  61   89  355  71.0  32.0       1
18  王冠廷  男   62  93   56  90   57  358  71.6  30.0       2
19  呂婉慧  女   86  89   52  89   74  390  78.0  12.0       1
20  莊子謙  男   88  69   73  83   76  389  77.8  13.0       0
21  蘇彥宏  男   73  59  100  84   87  403  80.6   7.0       1
22  李柏融  男   90  70   98  51   74  383  76.6  14.0       1
23  曾明軒  男   96  88   89  58   50  381  76.2  15.0       2
24  呂佳瑩  女  100  73   82  83   87  425  85.0   3.0       0
25  洪怡君  女   68  90   90  59   67  374  74.8  21.0       1
26  洪柏宏  男   58  69   81  65   88  361  72.2  27.0       1
27  江雅琪  女   63  53   86  77   60  339  67.8  41.0       1
28  郭怡萱  女   55  88   92  82   57  374  74.8  21.0       2
29  簡婉慧  女   92  55   88  52   53  340  68.0  40.0       3
30  楊靜宜  女   53  79   51  68   52  303  60.6  50.0       3
31  曾靜儀  女   59  62   75  53   73  322  64.4  45.0       2
32  蕭怡伶  女   82  77   77  98   98  432  86.4   2.0       0
33  洪裕豪  男   52  53   78  71   69  323  64.6  44.0       2
34  簡建宏  男   52  89   66  57   89  353  70.6  33.0       2
35  劉浩然  男   60  75   71  94   58  358  71.6  30.0       1
36  蕭浩宇  男   84  57   52  62   67  322  64.4  45.0       2
37  呂怡靜  女   67  97   76  63   93  396  79.2  11.0       0
38  邱宗翰  男   61  77   63  56   65  322  64.4  45.0       1
39  彭美慧  女   70  60   90  89   52  361  72.2  27.0       1
40  劉靜芬  女   92  99   55  77   85  408  81.6   5.0       1
41  許淑芬  女   71  70   73  63   66  343  68.6  38.0       0
42  邱裕豪  男   78  66   59  82   64  349  69.8  37.0       1
43  吳雅萍  女   70  97   82  96   58  403  80.6   7.0       1
44  施子軒  男   88  87   91  80  100  446  89.2   1.0       0
45  莊柏融  男   92  89   85  54   52  372  74.4  23.0       2
46  鍾浩銘  男   85  98   93  76   67  419  83.8   4.0       0
47  周美玲  女   69  59   75  78   90  371  74.2  24.0       1
48  劉婉婷  女   85  50   81  53   83  352  70.4  36.0       2
49  曾明哲  男   53  92   61  51   62  319  63.8  48.0       2
50  詹柏翰  男   72  92   51  52   69  336  67.2  43.0       2

In [5]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

     姓名 性別   國文  英文   數學  地理   歷史   總分    平均    排名  及格的科目數  不及格的科目名稱
1   劉彥宏  男   96  51   50  73   69  339  67.8  41.0       2     英文,數學
2   曾彥廷  男   71  80   60  51   52  314  62.8  49.0       2     地理,歷史
3   吳子睿  男   75  76   66  92   66  375  75.0  19.0       0         無
4   蕭志明  男   61  86   55  73   78  353  70.6  33.0       1        數學
5   王文傑  男   84  83   93  55   52  367  73.4  25.0       2     地理,歷史
6   朱冠霖  男   89  53   60  97   54  353  70.6  33.0       2     英文,歷史
7   謝欣蓉  女   79  66   84  80   57  366  73.2  26.0       1        歷史
8   羅淑芬  女   73  84   60  96   63  376  75.2  17.0       0         無
9   許美慧  女   60  74   52  96   61  343  68.6  38.0       1        數學
10  廖志豪  男   50  86   99  67  100  402  80.4   9.0       1        國文
11  葉柏翰  男   93  79   53  84   93  402  80.4   9.0       1        數學
12  呂承恩  男   83  89   55  60   88  375  75.0  19.0       1        數學
13  蘇雅婷  女   88  88   65  82   58  381  76.2  15.0       1        歷史
14  高浩宇  男   79  75   68  80   74  376  75.2  17.0       0         無
15  王婉茹  女   94  77   78  57   55  361  72.2  27.0       2     地理,歷史
16  莊承翰  男   79  89   60  90   90  408  81.6   5.0       0         無
17  黃裕傑  男   90  55   60  61   89  355  71.0  32.0       1        英文
18  王冠廷  男   62  93   56  90   57  358  71.6  30.0       2     數學,歷史
19  呂婉慧  女   86  89   52  89   74  390  78.0  12.0       1        數學
20  莊子謙  男   88  69   73  83   76  389  77.8  13.0       0         無
21  蘇彥宏  男   73  59  100  84   87  403  80.6   7.0       1        英文
22  李柏融  男   90  70   98  51   74  383  76.6  14.0       1        地理
23  曾明軒  男   96  88   89  58   50  381  76.2  15.0       2     地理,歷史
24  呂佳瑩  女  100  73   82  83   87  425  85.0   3.0       0         無
25  洪怡君  女   68  90   90  59   67  374  74.8  21.0       1        地理
26  洪柏宏  男   58  69   81  65   88  361  72.2  27.0       1        國文
27  江雅琪  女   63  53   86  77   60  339  67.8  41.0       1        英文
28  郭怡萱  女   55  88   92  82   57  374  74.8  21.0       2     國文,歷史
29  簡婉慧  女   92  55   88  52   53  340  68.0  40.0       3  英文,地理,歷史
30  楊靜宜  女   53  79   51  68   52  303  60.6  50.0       3  國文,數學,歷史
31  曾靜儀  女   59  62   75  53   73  322  64.4  45.0       2     國文,地理
32  蕭怡伶  女   82  77   77  98   98  432  86.4   2.0       0         無
33  洪裕豪  男   52  53   78  71   69  323  64.6  44.0       2     國文,英文
34  簡建宏  男   52  89   66  57   89  353  70.6  33.0       2     國文,地理
35  劉浩然  男   60  75   71  94   58  358  71.6  30.0       1        歷史
36  蕭浩宇  男   84  57   52  62   67  322  64.4  45.0       2     英文,數學
37  呂怡靜  女   67  97   76  63   93  396  79.2  11.0       0         無
38  邱宗翰  男   61  77   63  56   65  322  64.4  45.0       1        地理
39  彭美慧  女   70  60   90  89   52  361  72.2  27.0       1        歷史
40  劉靜芬  女   92  99   55  77   85  408  81.6   5.0       1        數學
41  許淑芬  女   71  70   73  63   66  343  68.6  38.0       0         無
42  邱裕豪  男   78  66   59  82   64  349  69.8  37.0       1        數學
43  吳雅萍  女   70  97   82  96   58  403  80.6   7.0       1        歷史
44  施子軒  男   88  87   91  80  100  446  89.2   1.0       0         無
45  莊柏融  男   92  89   85  54   52  372  74.4  23.0       2     地理,歷史
46  鍾浩銘  男   85  98   93  76   67  419  83.8   4.0       0         無
47  周美玲  女   69  59   75  78   90  371  74.2  24.0       1        英文
48  劉婉婷  女   85  50   81  53   83  352  70.4  36.0       2     英文,地理
49  曾明哲  男   53  92   61  51   62  319  63.8  48.0       2     國文,地理
50  詹柏翰  男   72  92   51  52   69  336  67.2  43.0       2     數學,地理

In [6]:
[subj for subj in [30, 40, 50] if subj <= 40] #list綜合表達式
fallings = []
','.join(fallings) if fallings else "無"

'無'